name: tandem-tango
channels:
  - defaults
dependencies:
  - lxml=5.2.2
  - ca-certificates=2024.7.2
  - molmass=2024.5.24
  - matplotlib =3.9.1
  - more-itertools =10.3.0
  - cvxpy=1.5.2
  - pandas=2.2.2
  - seaborn=0.13.2
  - snakemake=8.16.0
  - ipdb=0.13.13
  - pip:
    - pyteomics==4.7.2
    - xlsxwriter==3.2.0 
    - adjusttext==1.2.0
    - prefect==2.16.3