[project]
name = "tandem_tango"
version = "0.1.0"
description = "MS2 spectrum analysis and comparison"
authors = ["gkreder <gk@reder.io>"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "win-64", "linux-64"]

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<6.30"
lxml = ">=5.2.2,<5.3"
molmass = ">=2024.5.24,<2024.6"
matplotlib = ">=3.9.1,<3.10"
more-itertools = ">=10.3.0,<10.4"
cvxpy = ">=1.5.2,<1.6"
pandas = ">=2.2.2,<2.3"

[pypi-dependencies]
pyteomics = "*"
xlsxwriter = "*"
