[project]
name = "tandem_tango"
version = "0.1.0"
description = "MS2 spectrum analysis and comparison"
authors = ["gkreder <gk@reder.io>"]
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "win-64", "linux-64", "linux-aarch64"]

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<6.30"
lxml = ">=5.2.2,<5.3"
molmass = ">=2024.5.24,<2024.6"
matplotlib = ">=3.9.1,<3.10"
more-itertools = ">=10.3.0,<10.4"
cvxpy = ">=1.5.2,<1.6"
pandas = ">=2.2.2,<2.3"
seaborn = ">=0.13.2,<0.14"
snakemake = ">=8.16.0,<8.17"
ipdb = ">=0.13.13,<0.14"
tqdm = ">=4.66.5,<4.67"
openpyxl = ">=3.1.5,<4"

[pypi-dependencies]
pyteomics = ">=4.7.2"
xlsxwriter = ">=3.2.0 "
adjusttext = ">=1.2.0"
prefect = "==3.0.0"
